apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rh4q9i3sp-go 
  janus-idp.io/tekton: rh4q9i3sp-go
  backstage.io/kubernetes-id: rh4q9i3sp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rh4q9i3sp-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml