apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rh4q9i3sp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh4q9i3sp-go 
  name: rh4q9i3sp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rh4q9i3sp-go 
